# Generated by Django 5.0.6 on 2024-07-22 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='username_idx',
            old_name='users_user_usernam_65d164_idx',
        ),
    ]
